"""Removed uniqueness constraints

Revision ID: 7f358d1e78f2
Revises: f6d6d4fc24d7
Create Date: 2024-09-08 22:48:25.541854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f358d1e78f2'
down_revision = 'f6d6d4fc24d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poker_club_members')
    with op.batch_alter_table('poker_members', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poker_members', schema=None) as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    op.create_table('poker_club_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('second_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('course', sa.VARCHAR(length=150), nullable=True),
    sa.Column('year', sa.VARCHAR(length=150), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('second_name'),
    sa.UniqueConstraint('sex'),
    sa.UniqueConstraint('year')
    )
    # ### end Alembic commands ###
