"""Initial migration with QuantMathResult updates

Revision ID: f6d6d4fc24d7
Revises: 
Create Date: 2024-09-03 16:57:37.805673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f6d6d4fc24d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant_math_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mean_bayes_time', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mean_coupon_time', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mean_option_time', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mean_ev_time', sa.Float(), nullable=False))
        batch_op.drop_column('mean_time')
        batch_op.drop_column('time_per_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant_math_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_per_question', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('mean_time', sa.FLOAT(), nullable=False))
        batch_op.drop_column('mean_ev_time')
        batch_op.drop_column('mean_option_time')
        batch_op.drop_column('mean_coupon_time')
        batch_op.drop_column('mean_bayes_time')

    # ### end Alembic commands ###
